### ISSUE TITLE
Selected date showing wrong..

### ISSUE THREAD

**Issue by roychowdhurysourav23** [sambs/angular-sb-date-select#4]
I am facing an odd issue.I used this directive for date of birth and while selecting date of birth and saving data,Its working fine and while I am showing date its showing date+1 for an example

08-03-1990 fetching it but in drop-down showing 09-march-1990 
Please suggest some solution.

**Comment by sambs** [comment]
Can you confirm you that you are passing the date into the component as a string formatted YYYY-MM-DD?

**Comment by roychowdhurysourav23** [comment]
Yes. format is yyyy-mm-dd

**Comment by sambs** [comment]
I'm afraid I haven't been able to reproduce this @roychowdhurysourav23. Would you able to post an example on https://jsfiddle.net/?

**Comment by dddaaammmooo** [comment]
Have experienced the same issue, eg. '1980-01-02' comes up as '3 January 1980'.

Could it be a timezone issue?

**Comment by dddaaammmooo** [comment]
Interestingly, this is the rendered HTML... but the date is still showing as the 3rd *confused*
....
<option value="" disabled="" class="">Day</option>
<option value="0" label="1">1</option>
<option value="1" selected="selected" label="2">2</option>
<option value="2" label="3">3</option>
<option value="3" label="4">4</option>
....

**Comment by dddaaammmooo** [comment]
After a bit of googling it looks like it could be a browser issue: https://code.google.com/p/chromium/issues/detail?id=335876

I put in a hacky workaround by using "track by" in the "ng-options" for the date field

    var template = [
      '<div class="sb-date-select">',
        '<select class="sb-date-select-day sb-date-select-select" ng-class="selectClass" ng-model="val.date", ng-options="d for d in dates track by d">',
          '<option value disabled selected>Day</option>',
        '</select>',
        '<select class="sb-date-select-month sb-date-select-select" ng-class="selectClass" ng-model="val.month", ng-options="m.value as m.name for m in months">',
          '<option value disabled>Month</option>',
        '</select>',
        '<select class="sb-date-select-year sb-date-select-select" ng-class="selectClass" ng-model="val.year" ng-options="y for y in years">',
          '<option value disabled selected>Year</option>',
        '</select>',
      '</div>'
    ];

**Comment by sambs** [comment]
So you're only seeing this issue in Chrome? Which versions? I still haven't been able to reproduce this but I can't see any harm in adding your "track by" change if it fixes things for you @dddaaammmooo.

**Comment by dddaaammmooo** [comment]
No, i see the same issue happening on Chrome Version 46.0.2490.80 m and IE 11.0.10240.16431 both running on Windows 10. Works fine on Firefox however.

I don't think its an issue with your code as the DOM looks correct. And if you load the page and the date is wrong, changing the value of another select box 1 or 2 times times makes the browser update the incorrect value to reflect the one shown in the DOM even though the DOM for that field doesn't actually change.

Putting "track by" into the ng-options attribute definitely got around the problem though.

**Comment by dddaaammmooo** [comment]
Without "track by"

![date1](https://cloud.githubusercontent.com/assets/4394695/10817754/2764ca7c-7e90-11e5-93e5-970d716687e8.PNG)

With "track by"

![date2](https://cloud.githubusercontent.com/assets/4394695/10817768/48ac89e0-7e90-11e5-9793-d780b152782d.PNG)

**Comment by sambs** [comment]
Thanks for looking into this @dddaaammmooo.
